### PR TITLE
Fix Spanish dialect selection

### PR DESCRIPTION
**Pull request by mmcauliffe**
- [ x ] Updated `Unreleased` in `CHANGELOG.md` to reflect the changes in code or data.

### CODE REVIEW

**Comment by mmcauliffe** [comment]
One open question I have is whether to include additional country selectors for Latin America (i.e. Columbia, Chile, etc) to the scrape's config, but I don't know how prevalent these are wiktionary or if they're wanted in the wider Latin America dialect file.

**Review by kylebgorman — COMMENTED** [review]
LGTM and I appreciate the new test, which is very needed.

Okay, so I think the right way to test this though is to run the big scrape on Spanish and incorporate changes into the PR. For that you'd install (from this PR), navigate to `data/scrape` and issue `./scrape --restriction spa && ./postprocess` and wait (about 12-24 hours), then stage and commit the changed files. Is this feasible on your end?

**Comment by kylebgorman** [comment]
> One open question I have is whether to include additional country selectors for Latin America (i.e. Columbia, Chile, etc) to the scrape's config, but I don't know how prevalent these are wiktionary or if they're wanted in the wider Latin America dialect file.

We don't have any discoverability for dialect strings. Ideally there'd be some way to get a list of them in descending frequency order and then you could manually cluster and write back into `languages.json`. Nice feature request though.

**Comment by mmcauliffe** [comment]
Sure, I can run that in the next couple of days.  I did do some work for getting single parse for multiple dialects working, but it's a bit hacky and I'll rerun the scape using just this current branch.

**Comment by kylebgorman** [comment]
> Sure, I can run that in the next couple of days. I did do some work for getting single parse for multiple dialects working, but it's a bit hacky and I'll rerun the scape using just this current branch.

Excited to see this, this will be a huge improvement we've wanted forever.

**Review by kylebgorman — APPROVED** [review]
LGTM, big thanks to you for this.

**Pull request merged**
