### PR TITLE
[eng][upstream cleaning]affricate tie bars

### PR DESCRIPTION
**Pull request by Othergreengrasses**
- [ ] Updated `Unreleased` in `CHANGELOG.md` to reflect the changes in code or data.

### CODE REVIEW

**Comment by kylebgorman** [comment]
Hi @Othergreengrasses, I'm only seeing the change to `data/scrape/scrape.py`, which has nothing to do with the description.

(Note you should run `black -l79` over the project, and also update the changelog file before this is ready for review.)

**Comment by Othergreengrasses** [comment]
Yes, I did a wrong commit earlier. I corrected the commit now. Let me know black -179 is still required or not. Thank you!

**Comment by kylebgorman** [comment]
This part here (which you should be able to see too; let me know if you can’t) tells me it is still needed. Though this is only if you’re checking in Python.
9EE412A3-2F54-4963-86EF-22CDEC2991FE

**Comment by jacksonllee** [comment]
Hello, I'm chiming in here in case what's happening is a bit obscure.

* The CircleCI failure: This PR branch appears to be behind when compared to the upstream's master branch. The "black" error should go away once you merge upstream's master back into your branch here.
* Since a new data TSV is being added here (thank you for this!), I _believe_ there are other files that have to be updated as well for consistency, e.g., `data/scrape/tsv_summary.tsv`, `data/scrape/README.md`, and possibly also `data/scrape/lib/languages.json`? See the readme at [data/scrape/lib](https://github.com/CUNY-CL/wikipron/tree/master/data/scrape/lib) -- there's the script `data/scrape/postprocess` that you could run to update some f these files programmatically.

**Comment by kylebgorman** [comment]
Thanks Jackson. Let me also add that I expected 4 different English files would be updated with this: broad and narrow, filtered and not filtered.

@Othergreengrasses has been doing valuable upstream consistency work on English wrt the use of tie bars, and the goal of this PR is to lock them into our English lexicons.

**Comment by kylebgorman** [comment]
Thanks Jackson. Let me also add that I expected 4 different English files would be updated with this: broad and narrow, filtered and not filtered.

@Othergreengrasses has been doing valuable upstream consistency work on English wrt the use of tie bars, and the goal of this PR is to lock them into our English lexicons.

**Comment by kylebgorman** [comment]
Closing this out after discussion with the author. We'll start again from scratch.

**Pull request closed without merging**
