### PR TITLE
Regenerated English data

### PR DESCRIPTION
**Pull request by annapiab**
- [x] Updated `Unreleased` in `CHANGELOG.md` to reflect the changes in code or data.

### CODE REVIEW

**Review by kylebgorman — COMMENTED** [review]
So this looks pretty good. Here a few things to address. Once you do, I'll spot-check the new data and then we should be done. 

1. As indicated in the PR description, you need to update the CHANGELOG.md file (it should be obvious what to do there, just follow the format and keep it brief) and click the checkbox in the PR description above. (then add, commit and push)
2. The test that is failing is saying the summary data is not up to date with what you're checking in. To fix that (hopefully), navigate to `data/scrape` and run `./postprocess` then check in (add commit push) the affected files (should be a single TSV file and the README in that directory)
3. Please remove `unscraped.json` from the PR (`git rm` it then commit and push).

**Comment by annapiab** [comment]
Hi Kyle,

I updated these, but the CircleCI tests keep failing. Is there anything else I should try?

Best,
Annapia.

Da: Kyle Gorman ***@***.***>
Data: domenica, 1 settembre 2024 alle ore 12:18 PM
A: CUNY-CL/wikipron ***@***.***>
Cc: Annapia Borraccino ***@***.***>, Author ***@***.***>
Oggetto: [EXTERNAL]Re: [CUNY-CL/wikipron] Regenerated English data (PR #555)
***ATTENTION: This email came from an external source. Do not open attachments or click on links from unknown senders or unexpected emails.***


@kylebgorman commented on this pull request.

So this looks pretty good. Here a few things to address. Once you do, I'll spot-check the new data and then we should be done.

  1.  As indicated in the PR description, you need to update the CHANGELOG.md file (it should be obvious what to do there, just follow the format and keep it brief) and click the checkbox in the PR description above. (then add, commit and push)
  2.  The test that is failing is saying the summary data is not up to date with what you're checking in. To fix that (hopefully), navigate to data/scrape and run ./postprocess then check in (add commit push) the affected files (should be a single TSV file and the README in that directory)
  3.  Please remove unscraped.json from the PR (git rm it then commit and push).

**Review by kylebgorman — COMMENTED** [review]
Please click the checkbox in the PR description now that you've updated the changelog. (It's clickable.)

**Review by kylebgorman — COMMENTED** [review]
It looks like you should revert the change in `languages.json`, which broke something. (This shouldn't have been checked in in the first place.) I think what you'll do is `git reset HEAD data/scrape/lib/languages.json` assuming you're in the top-level directory...adjust the path if that's not right) and then commit. You'll know you have it when `languages.json` doesn't appear in the list of modified files. I predict tests will pass then.

**Comment by annapiab** [comment]
Hi Kyle, I have tried reverting the changes in `languages.json`, but no matter what I do `git status` is always telling me _working tree clean_, so I am assuming nothing changes. I am sure of the path too. Is there an another alternative?

**Comment by kylebgorman** [comment]
> Hi Kyle, I have tried reverting the changes in `languages.json`, but no matter what I do `git status` is always telling me _working tree clean_, so I am assuming nothing changes. I am sure of the path too. Is there an another alternative?

I just went in on GitHub and manually reverted the changes to `languages.json`. Will merge if the tests pass.

**Comment by kylebgorman** [comment]
So, I see a test failing right now but I am for unrelated reasons certain it has nothing to do with your PR.  (In fact it's happening at head.) Since that's the only test failure I see, I will now merge. Thanks for the submission.

**Comment by annapiab** [comment]
I was trying to look into it as well, but I am unsure of what the issue might have been. Thanks for your help, Kyle!

**Pull request merged**
