### PR TITLE
Big Scrape 2022

### PR DESCRIPTION
**Pull request by jacksonllee**
Major updates from this PR:

* Ran the Big Scrape 2022.
* Added --fresh in scrape.py to facilitate running the big scrape in batches.

Note:

* Languages not updated in this PR: `yue` (Cantonese) and `nan` (Min Nan). It looks like scraping these two languages didn't return any data. Since these two languages need custom XPath extractor support, possibly something upstream at Wiktionary has changed? I'm fine to punt on `yue` and `nan` for a future PR.
* The updated Latin TSVs has a whole lot more new data than any other languages. @kylebgorman Would you be able to confirm if the Latin updates are legit or not? If not, I'll un-do the Latin file changes for now and we'll handle Latin in a future PR.

- [x] Updated `Unreleased` in `CHANGELOG.md` to reflect the changes in code or data.

### CODE REVIEW

**Comment by kylebgorman** [comment]
Yeah, let's punt on `yue` and `nan`.

I'm having trouble seeing the Latin changes. GitHub won't show me them (files too big), and then when I clone the PR and checkout the right branch, the files are the same size as what's at HEAD.

**Comment by jacksonllee** [comment]
> when I clone the PR and checkout the right branch, the files are the same size as what's at HEAD

I do see the diffs between this PR branch and `master`. This is what the GitHub web GUI shows as well:

Screen Shot 2022-03-01 at 11 36 11 PM

**Comment by kylebgorman** [comment]
GitHub won't show me the diff---it's too large. Any chance you could
generate diffs on your side and like, email them to me?

K

**Comment by kylebgorman** [comment]
Hi @jacksonllee any chance you can send me the Latin files? I can't read them in GitHub (too big) and locally they're identical to HEAD for me.

**Comment by jacksonllee** [comment]
It'd seem unwieldy to me to email large text files around. You should be able to use `git diff` from the terminal to get the diff. Specifically, once you've pulled down this branch locally, then some variation of `git diff 17f4433 035eb0d` should do the trick. (035eb0d is the current latest commit on master, while 17f4433 is the current latest commit from this PR branch.)

For the Latin files, you can ask `git diff` to show the diffs for a specific file. For instance,

```bash
git diff 17f4433 035eb0d -- data/scrape/tsv/lat_latn_clas_broad.tsv
```

would output the diff to stdout. If having the output saved in a text file makes it easier for review, `git diff` has a `--output` flag:

```bash
git diff --output=lat_latn_clas_broad.txt 17f4433 035eb0d -- data/scrape/tsv/lat_latn_clas_broad.tsv
```

Here are the file paths of the Latin files that have been updated:

```
data/scrape/tsv/lat_latn_clas_broad.tsv
data/scrape/tsv/lat_latn_clas_broad_filtered.tsv
data/scrape/tsv/lat_latn_clas_narrow.tsv
data/scrape/tsv/lat_latn_eccl_broad.tsv
data/scrape/tsv/lat_latn_eccl_narrow.tsv
data/scrape/tsv/lat_latn_vulg_broad.tsv
data/scrape/tsv/lat_latn_vulg_narrow.tsv
```

**Comment by kylebgorman** [comment]
Thanks for the tip Jackson. I'm not sure what I was doing wrong earlier but I couldn't get it to show me the diff earlier.

Okay, they did in fact improve the Latin data (just noting here for reference):

* _h_ is silent (correctly, probably)
* glides are written [j, w] instead of as semivowels with breves (definitely correct)

so I'm good to go ahead with this.

**Review by kylebgorman — APPROVED** [review]
LGTM, thanks so much Jackson.

**Comment by kylebgorman** [comment]
For fun, I just did a quick analysis on the TSV file. We now have 245
languages (+ 16 non-null dialects), 39 scripts, and just over 3.5 million
entries. (For comparison, the scrape from early 2021 had 3.1m entries.)

K

**Comment by jacksonllee** [comment]
> For fun, I just did a quick analysis on the TSV file. We now have 245
languages (+ 16 non-null dialects), 39 scripts, and just over 3.5 million
entries. (For comparison, the scrape from early 2021 had 3.1m entries.)

Sweet. I wonder if it's worth setting up something to facilitate getting these "KPI" numbers. I see two steps:

* Have a script or something that would churn out these numbers you've quoted, and just show them in stdout. Run this script as part of CI. If we feel like updating the README or anywhere where we quote these numbers, then we can manually do that. If we want something fancier and more automatic, next bullet point...
* Set up a bot (a GitHub action or something else?) that would regularly scan the repo and create a PR to update the documentation with these numbers, leveraging code that'd have been ready from the previous bullet point.

Sounds like you may already have code for the first bullet point? 🙂

**Comment by kylebgorman** [comment]
Great idea!

I can make a gist version of part 1. (I did it hackishly in R---I'll do it
right this time.) I don't have the expertise for part 2 yet.

**Comment by kylebgorman** [comment]
* [Gist](https://gist.github.com/kylebgorman/a32fd2c91c862cd508de9b14fbba80dd) to get someone started on this.
* [Issue](https://github.com/CUNY-CL/wikipron/issues/465)

**Pull request merged**
