### PR TITLE
Updates character filtering and rescrapes Makasar

### LINKED ISSUE #416: Common characters and _detect_best_script_name
While scraping Makasar (PR #415), I've encountered the following default behavior:

1. We currently have strict mode turned on by default `_detect_best_script_name`, which is sensible. This makes sure that all the characters in a word come from the same script.
2. Because of (1), we are failing to detect about half of Makasar words (200+) in Latin orthography, where the apostrophe `'` signifies glottal stop.

I was under the impression that the plan was to allow a set of configurable (per-language) common characters to be allowed inside `_detect_best_script_name`. Perhaps I misunderstood the original plan?

I suppose the current behavior may be too restrictive as there are plenty of languages where the common Latin apostrophe is used.

### PR DESCRIPTION
**Pull request by lfashby**
- [x] Updated `Unreleased` in `CHANGELOG.md` to reflect the changes in code or data.

It is good that we noticed this now as opposed to during/after a 'Big Scrape'! 

Closes #416

### CODE REVIEW

**Review by kylebgorman — APPROVED** [review]
LGTM

**Comment by kylebgorman** [comment]
LGTM but maybe you want @cgibson6279's thumbs up too.

**Comment by lfashby** [comment]
Is our CircleCI stuff broken now that the repo has moved?

**Comment by cgibson6279** [comment]
Yup. Looks good to me! Do I just `Squash and merge` to approve?

**Comment by kylebgorman** [comment]
> Is our CircleCI stuff broken now that the repo has moved?

I don't think so? It ran for Yeonju's PR 36 minutes ago: https://app.circleci.com/pipelines/github/CUNY-CL/wikipron?branch=master

**Comment by kylebgorman** [comment]
> Yup. Looks good to me! Do I just `Squash and merge` to approve?

To approve, click on "Files changed" in the top right, then under "Review changes" click the "Approve" radio button. Then yes, squash and merge.

**Review by cgibson6279 — APPROVED** [review]

**Pull request merged**
